version: '3.4'

services:
  cef_client_features_data:
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
      MSSQL_PID: Express

  cef_client_features_app:
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 5001
    ports:
      - "5000:80"
      - "5001:443"
